export const config = {
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  GOOGLE_FORM_URL: process.env.GOOGLE_FORM_URL,
  GOOGLE_SUB_FORM_URL: process.env.GOOGLE_SUB_FORM_URL,
  CALENDLY_SCHEDULING_URL: process.env.CALENDLY_SCHEDULING_URL,
  YOUR_TELEGRAM_CHAT_ID: process.env.YOUR_TELEGRAM_CHAT_ID
};
